### ISSUE TITLE
Agent build fails (missing std::)

### ISSUE THREAD

**Issue by vilhjalmur89** [eProsima/Firmware#11]
Building the agent fails with the the error:
`error: ‘cout’ was not declared in this scope`

The publishers and subscribers generated by 'fastrtpsgen' are missing std:: in front of some cout and endl statements.

**Comment by vicentemonge** [comment]
HI, I can't reproduce the problem. I executed that:
```shell
git clone https://github.com/eProsima/Firmware.git FFFirmware
cd FFFirmware/
python Tools/generate_microRTPS_bridge.py --send msg/sensor_combined.msg --receive msg/sensor_combined.msg
./micrortps_install.sh /home/vmonge/Workspace/PX4/MicroRTPS_agent/micrortps_agent_issue /home/vmonge/Workspace/Fast-RTPS/install/bin
cd /home/vmonge/Workspace/PX4/MicroRTPS_agent/micrortps_agent_issue/build/
cmake ../ -DCMAKE_PREFIX_PATH=/home/vmonge/Workspace/Fast-RTPS/install && make all
```

**Comment by vilhjalmur89** [comment]
Yes, it is only in the files generated by 'fastrtpsgen', so it doesn't happen when received and sent messages are the same. For example, I get the error with 
`python Tools/generate_microRTPS_bridge.py --send msg/sensor_combined.msg`

**Comment by vicentemonge** [comment]
For me is the same and it's compiling too... Are you working with the last version of eProsima/Firmware?

**Comment by vilhjalmur89** [comment]
Aha, fastrtpsgen was out of date.
Thanks!

**Comment by vilhjalmur89** [comment]
So when I updated Fast-RTPS I used `cmake -DTHIRDPARTY=ON ..` as it is in the instructions on [github](https://github.com/eProsima/Fast-RTPS#installation-from-source), but I needed `cmake -DTHIRDPARTY=ON -DBUILD_JAVA=ON ..` to update fastrtpsgen as well. 
We should probably make this clear in the documentation.

**Comment by vicentemonge** [comment]
We add some changes in the documentation in eProsima/Fast-RTPS-docs@95efccc1a265bc10a10305a7bdad78d57cb643a0

Thanks for the feedback!
