### ISSUE TITLE
Support for multiple topics

### ISSUE THREAD

**Issue by vilhjalmur89** [eProsima/Firmware#2]
I think being able to send messages back and forth over multiple topics is the only feature we need to start using this. I guess generating a single transmitter/receiver from a list of .msg-files, and wrapping the message with the topic-ID would be possible. What do you think?

**Comment by vilhjalmur89** [comment]
I took a quick stab at adding a topic_ID to the payload.

https://github.com/eProsima/Firmware/pull/4

**Comment by vicentemonge** [comment]
Done through already merged @vilhjalmur89 pull request 99cdabfca1413fa93b026129fa424116bad6d9e4
