### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by mcharleb** [eProsima/Firmware#6]
README_eprosima.rst:

- Tools/generate_microRTPS_support_general.py doesn't exist. It now seems to be generate_microRTPS_bridge.py
- examples/micrortps_transmitter doesn't exist in cmake/configs/nuttx_px4fmu-v4_default.cmake. Do you mean add it? What is examples/micrortps_client for? It doesn't exist in the tree and nothing refers to it?
- Run:
  - python Tools/generate_microRTPS_bridge.py -r msg/sensor_baro.msg -s msg/sensor_combined.msg
  - There is no general_uRTPS_UART_transmitter.cpp created so it cannot be copied to src/examples/micrortps_transmitter

For the RPi portion:
- Run:
  - /path/to/Fast-RTPS/fastrtpsgen/scripts/fastrtpsgen -example x64Linux2.6gcc *.idl
  - This fails because it cant find Fast-RTPS/fastrtpsgen/scripts/../share/fastrtps/fastrtpsgen.jar
    - there is no share directory in Fast-RTPS/fastrtpsgen when built from git://github.com/eProsima/Fast-RTPS.git

**Comment by vicentemonge** [comment]
Thanks for the contribution, already solved.
